# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

# Inspiration
# https://github.com/actions/starter-workflows/blob/main/ci/docker-publish.yml

name: build-docker-image

on:
  push:
  #   branches: [ main ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  release:
    types: [published, created, edited]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Login against a Docker registry except on PR
      # https://github.com/marketplace/actions/docker-login
      # https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        if: |
          github.event_name != 'pull_request' 
        # if: |
        #   github.event_name != 'pull_request'  ||
        #   github.repository_owner == 'ptarmiganlabs'
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      # Extract metadata (tags, labels) for Docker
      # https://github.com/marketplace/actions/docker-metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          # images: ${{ env.IMAGE_NAME }}
          images: ${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Show Docker tags that will be used
        run: echo '${{ steps.meta.outputs.tags }}'

      - name: Show Docker labels that will be used
        run: echo '${{ steps.meta.outputs.labels }}'

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./src
          # file: Dockerfile
          platforms: |
            linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Send job status to MQTT when done
        uses: potaesm/github-actions-mqtt-request@1.0.0
        if: always()
        env:
          JOB_STATUS: ${{ job.status }}
          NODE_VERSION: ${{ matrix.node }}
        with:
          url: ${{ secrets.PUBLIC_MQTT_BROKER_URL }}
          topic: control/github_actions_action_runner
          payload: '{ "type":"docker-build", "repo": "${{ github.repository }}", "job": "${{ github.job }}", "workflow": "${{ github.workflow }}", "nodeVersion": "${{ env.NODE_VERSION }}","status":"${{ env.JOB_STATUS }}" }'
          # wsOptions: '{ "port": 443 }'
          username: ${{ secrets.PUBLIC_MQTT_BROKER_USER }}
          # password: p@ssw0rd
          connectTimeout: 30000


    env:
      CI: true
