name: release-please
on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2.32.0
        if: |
          github.repository_owner == 'ptarmiganlabs'
        with:
          token: ${{ secrets.PAT }}
          release-type: node
          package-name: butler-sheet-icons
          path: src
