name: test-macos
on:
  push:
    branches:
      - main
jobs:
  test-macos:
    runs-on: [self-hosted, macOS]
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install
    - name: Run tests
      run: npm test
      env:
        BSI_CONTENT_LIBRARY: 'abc 123'
        BSI_HOST: ${{ secrets.BSI_HOST }}
        BSI_APP_ID: 'a3e0f5d2-000a-464f-998d-33d333b175d7'
        BSI_LOGON_USER_DIR: ${{ secrets.BSI_LOGON_USER_DIR }}
        BSI_LOGON_USER_ID: ${{ secrets.BSI_LOGON_USER_ID }}
        BSI_LOGON_PWD: ${{ secrets.BSI_LOGON_PWD }}
        BSI_TEST_TIMEOUT: 120000
        BSI_CERT_FILE: ${{ secrets.BSI_CERT_FILE }}
        BSI_CERT_KEY_FILE: ${{ secrets.BSI_CERT_KEY_FILE }}
        # BSI_CERT: ${{ secrets.BSI_CERT }}
        # BSI_CERT_KEY: ${{ secrets.BSI_CERT_KEY }}
        