name: test-windows
on:
  push:
    branches:
      - main

# Test case below assumes a) Node.js 14.x and b) Jest are installed globally on the server running the tests.
# Install Jest with npm install jest --global
# Test runner is in this case running on one of the servers that make up the Sense cluster.
jobs:
  test-winsrv2016-nodejs14:
    runs-on: [self-hosted, windows, X64, winsrv2016, nodejs14]
    steps:
    - uses: actions/checkout@v2
    - name: Switch to target Node version
      run: nvm use 14.17.1
    - name: Debugging 1
      run: dir
      working-directory: src
    - name: Install modules
      run: npm install
      working-directory: src
    - name: Debugging 2
      run: dir
      working-directory: src
    - name: Run tests
      run: npm run test
      working-directory: src
      env:
        BSI_CONTENT_LIBRARY: 'abc 123'
        BSI_HOST: ${{ secrets.BSI_HOST }}
        BSI_APP_ID: 'a3e0f5d2-000a-464f-998d-33d333b175d7'
        BSI_LOGON_USER_DIR: ${{ secrets.BSI_LOGON_USER_DIR }}
        BSI_LOGON_USER_ID: ${{ secrets.BSI_LOGON_USER_ID }}
        BSI_LOGON_PWD: ${{ secrets.BSI_LOGON_PWD }}
        BSI_TEST_TIMEOUT: 120000
        BSI_PREFIX: form
        BSI_CERT_FILE: 'C:\ProgramData\Qlik\Sense\Repository\Exported Certificates\.Local Certificates\client.pem'
        BSI_CERT_KEY_FILE: 'C:\ProgramData\Qlik\Sense\Repository\Exported Certificates\.Local Certificates\client_key.pem'
        # BSI_CERT: ${{ secrets.BSI_CERT }}
        # BSI_CERT_KEY: ${{ secrets.BSI_CERT_KEY }}
        