name: test-windows
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-winsrv:
    runs-on:
      - self-hosted
      - ${{ matrix.os }}
      - ${{ matrix.architecture }}
      - sp53
    strategy:
      matrix:
        node:
          - lts/*
        architecture:
          - x64
        os:
          - winsrv-2016

    steps:
      - name: Send job status to MQTT (starting job)
        uses: potaesm/github-actions-mqtt-request@1.0.0
        if: always()
        env:
          JOB_CONCLUSION: ${{ job.status }}
          NODE_VERSION: ${{ matrix.node }}
        with:
          url: mqtt://${{ secrets.MQTT_ONPREM_BROKER_IP_PORT }}
          topic: control/sp53/pro2-win2/action-runner
          payload: '{ "type":"ci-test", "repo": "${{ github.repository }}", "job": "${{ github.job }}", "workflow": "${{ github.workflow }}", "nodeVersion": "${{ env.NODE_VERSION }}","status": "in_progress","conclusion":"${{ env.JOB_CONCLUSION }}" }'
          connectTimeout: 30000

      - uses: actions/checkout@v3

      - name: Debugging 1
        run: dir
        working-directory: src

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install modules
        run: npm install
        working-directory: src

      - name: Make sure Jest is installed
        run: npm install jest

      - name: Debugging 2
        run: dir
        working-directory: src

      - name: Run tests
        run: npm run test
        working-directory: src
        env:
          BSI_CONTENT_LIBRARY: "abc 123"
          BSI_HOST: ${{ secrets.BSI_HOST }}
          BSI_PREFIX: ${{ secrets.BSI_PREFIX }}
          BSI_APP_ID: "a3e0f5d2-000a-464f-998d-33d333b175d7"
          BSI_LOGON_USER_DIR: ${{ secrets.BSI_LOGON_USER_DIR }}
          BSI_LOGON_USER_ID: ${{ secrets.BSI_LOGON_USER_ID }}
          BSI_LOGON_PWD: ${{ secrets.BSI_LOGON_PWD }}
          BSI_TEST_TIMEOUT: ${{ secrets.BSI_TEST_TIMEOUT }}
          BSI_CERT_FILE: ${{ secrets.BSI_WIN_CERT_FILE }}
          BSI_CERT_KEY_FILE: ${{ secrets.BSI_WIN_CERT_KEY_FILE }}
          BSI_INCLUDE_SHEET_PART: ${{ secrets.BSI_INCLUDE_SHEET_PART }}
          BSI_CLOUD_TENANT_URL: ${{ secrets.BSI_CLOUD_TENANT_URL }}
          BSI_CLOUD_API_KEY: ${{ secrets.BSI_CLOUD_API_KEY }}
          BSI_CLOUD_LOGON_USERID: ${{ secrets.BSI_CLOUD_LOGON_USERID }}
          BSI_CLOUD_LOGON_PWD: ${{ secrets.BSI_CLOUD_LOGON_PWD }}
          BSI_CLOUD_APP_ID: ${{ secrets.BSI_CLOUD_APP_ID }}
          BSI_CLOUD_COLLECTION_ID: ${{ secrets.BSI_CLOUD_COLLECTION_ID }}

      - name: Send job status to MQTT when done
        uses: potaesm/github-actions-mqtt-request@1.0.0
        if: always()
        env:
          JOB_CONCLUSION: ${{ job.status }}
          NODE_VERSION: 16
        with:
          url: mqtt://${{ secrets.MQTT_ONPREM_BROKER_IP_PORT }}
          topic: control/sp53/pro2-win2/action-runner
          payload: '{ "type":"ci-test", "repo": "${{ github.repository }}", "job": "${{ github.job }}", "workflow": "${{ github.workflow }}", "nodeVersion": "${{ env.NODE_VERSION }}","status": "completed","conclusion":"${{ env.JOB_CONCLUSION }}" }'
          connectTimeout: 30000
